### ISSUE TITLE
Photos added to a checkin after it has been added to Thinkup are not stored

### ISSUE THREAD

**Issue by AaronKalair** [ThinkUpLLC/ThinkUp#1390]
If you use Thinkup to capture a checkin and then add another photo to the checkin on foursquare Thinkup does not retrieve it. 

This is due to the if statement on line 376 of FoursquareCrawler.php which ensures that all photos have an associated post id

Full credit to @hidgw on Twitter for finding this bug

**Comment by dgw** [comment]
Foursquare isn't in the core plugin set any more, sadly, so this should be closed.
