### ISSUE TITLE
g+ plugin setup - issue with tu_users insertion

### ISSUE THREAD

**Issue by amygdala** [ThinkUpLLC/ThinkUp#1526]
With thinkup-2.0-beta.4 (clean install) I noticed the following error when I was activating the g+ plugin:

Database error! ThinkUp could not execute the following query: INSERT INTO tu_users (user_id, user_name, full_name, avatar, location, description, url, is_protected, follower_count, post_count, found_in, joined, network ) VALUES ( :user_id, :username, :full_name, :avatar, :location, :description, :url, :is_protected, :follower_count, :post_count, :found_in, :joined, :network ) PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'joined' at row 1

(I'm not sure what impact this error had, as the plugin seems to be gathering data okay).

**Comment by luisnomad** [comment]
I am still getting this, when activating Instagram
