### ISSUE TITLE
New Insight: Your bestie this month

### ISSUE THREAD

**Issue by adampash** [ThinkUpLLC/ThinkUp#1990]
# One-liner

Who you've interacted with most in the past month.

# Full explainer

(I'm using "bestie" as a shorthand throughout b/c "person you interact with most over time" is a mouthful.)

It's easy to have a sense of who you've interacted with a lot recently (everyone can remember last week), but your social interactions over time can be surprising and revealing. Ideally, the user should feel a sense of connection.

# Audience

This insight works on all networks. It best serves users with more activity but doesn't exclude users with less activity.

# How often this insight runs

- [ ] One-time only, if it's never appeared before
- [ ] First crawl only
- [ ] Daily
- [ ] Weekly
- [x] Monthly
- [ ] Yearly
- [ ] Triggered by a data event

27th for Twitter, 29th for Facebook, 25th for Instagram

# Headline / Body

Let's just use the previewer here.

## Twitter first-run/new bestie

![](https://shares.thinkup.com/insight?headline=%40spike%20is%20%40angel%27s%20Twitter%20bestie&body=Best%20friends%20chat%20each%20other%20up%20about%20every%20topic%20under%20the%20sun-just%20like%20%40spike%20and%20%40angel.%20In%20the%20past%20month%2C%20%40spike%20tweeted%20at%20%40angel%20%3Cstrong%3E3%20times%3C%2Fstrong%3E%2C%20and%20%40angel%20replied%20%3Cstrong%3E5%20times%3C%2Fstrong%3E.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20How%20cute!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=mint&embed=embed-none&preview=1)

[Edit this](https://thinkup.thinkup.com/insight_tester.php?headline=%40spike%20is%20%40angel%27s%20Twitter%20bestie&body=Best%20friends%20chat%20each%20other%20up%20about%20every%20topic%20under%20the%20sun-just%20like%20%40spike%20and%20%40angel.%20In%20the%20past%20month%2C%20%40spike%20tweeted%20at%20%40angel%20%3Cstrong%3E3%20times%3C%2Fstrong%3E%2C%20and%20%40angel%20replied%20%3Cstrong%3E5%20times%3C%2Fstrong%3E.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20How%20cute!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=mint&embed=embed-none&preview=1)

## Twitter bestie streak

![](https://shares.thinkup.com/insight?headline=%40spike%20is%20still%20%40angel%27s%20Twitter%20bestie&body=BFFs%20love%20to%20chat%2C%20and%20for%20%3Cstrong%3E3%20months%20straight%3C%2Fstrong%3E%2C%20%40spike%20has%20been%20%40angel%27s%20Twitter%20bestie.%20In%20the%20past%20month%2C%20%40spike%20tweeted%20at%20%40angel%203%20times%2C%20and%20%40angel%20replied%205%20times.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20How%20cute!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=caramel&embed=embed-none&preview=1)

[Edit this](https://thinkup.thinkup.com/insight_tester.php?headline=%40spike%20is%20still%20%40angel%27s%20Twitter%20bestie&body=BFFs%20love%20to%20chat%2C%20and%20for%20%3Cstrong%3E3%20months%20straight%3C%2Fstrong%3E%2C%20%40spike%20has%20been%20%40angel%27s%20Twitter%20bestie.%20In%20the%20past%20month%2C%20%40spike%20tweeted%20at%20%40angel%203%20times%2C%20and%20%40angel%20replied%205%20times.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20How%20cute!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=caramel&embed=embed-none&preview=1)

## Facebook first-run/new bestie

![](https://shares.thinkup.com/insight?headline=Xander%20Harris%20is%20Willow%20Rosenberg%27s%20Facebook%20BFF&body=Friends%20comment%20on%20friends%27%20status%20updates-friends%20like%20Xander%20Harris%20and%20Willow%20Rosenberg.%20%20In%20the%20past%20month%2C%20Xander%20Harris%20commented%20on%20Willow%20Rosenberg%27s%20status%20updates%20%3Cstrong%3E10%20times%3C%2Fstrong%3E%2C%20more%20than%20anyone%20else.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=mint&embed=embed-none&preview=1)

[Edit this](https://thinkup.thinkup.com/insight_tester.php?headline=Xander%20Harris%20is%20Willow%20Rosenberg%27s%20Facebook%20BFF&body=Friends%20comment%20on%20friends%27%20status%20updates-friends%20like%20Xander%20Harris%20and%20Willow%20Rosenberg.%20%20In%20the%20past%20month%2C%20Xander%20Harris%20commented%20on%20Willow%20Rosenberg%27s%20status%20updates%20%3Cstrong%3E10%20times%3C%2Fstrong%3E%2C%20more%20than%20anyone%20else.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=mint&embed=embed-none&preview=1)

## Facebook bestie streak

![](https://shares.thinkup.com/insight?headline=Xander%20Harris%20is%20still%20Willow%20Rosenberg%27s%20Facebook%20bestie&body=BFFs%20love%20to%20chat%2C%20and%20for%20%3Cstrong%3E3%20months%20straight%3C%2Fstrong%3E%20Xander%20Harris%20has%20been%20Willow%20Rosenberg%27s%20Facebook%20bestie.%20In%20the%20past%20month%2C%20Xander%20Harris%20commented%20on%20Willow%20Rosenberg%27s%20status%20updates%2010%20times%2C%20more%20than%20anyone%20else.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=mint&embed=embed-none&preview=1)

[Edit this](https://thinkup.thinkup.com/insight_tester.php?headline=Xander%20Harris%20is%20still%20Willow%20Rosenberg%27s%20Facebook%20bestie&body=BFFs%20love%20to%20chat%2C%20and%20for%20%3Cstrong%3E3%20months%20straight%3C%2Fstrong%3E%20Xander%20Harris%20has%20been%20Willow%20Rosenberg%27s%20Facebook%20bestie.%20In%20the%20past%20month%2C%20Xander%20Harris%20commented%20on%20Willow%20Rosenberg%27s%20status%20updates%2010%20times%2C%20more%20than%20anyone%20else.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=mint&embed=embed-none&preview=1)

## Instagram first-run/new bestie

![](https://shares.thinkup.com/insight?headline=capndesign%20is%20ginatrapani%27s%20Instagram%20bestie&body=Friends%20have%20a%20lot%20to%20say%20about%20friends%27%20Instagram%20photos%3A%20like%20capndesign%20and%20ginatrapani.%20%20In%20the%20past%20month%2C%20capndesign%20commented%20on%20ginatrapani%27s%20photos%20%3Cstrong%3E10%20times%3C%2Fstrong%3E%2C%20more%20than%20anyone%20else.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=salmon&embed=embed-none&preview=1)

[Edit this](https://thinkup.thinkup.com/insight_tester.php?headline=capndesign%20is%20ginatrapani%27s%20Instagram%20bestie&body=Friends%20have%20a%20lot%20to%20say%20about%20friends%27%20Instagram%20photos%3A%20like%20capndesign%20and%20ginatrapani.%20%20In%20the%20past%20month%2C%20capndesign%20commented%20on%20ginatrapani%27s%20photos%20%3Cstrong%3E10%20times%3C%2Fstrong%3E%2C%20more%20than%20anyone%20else.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=mint&embed=embed-none&preview=1)

## Instagram bestie streak

![](https://shares.thinkup.com/insight?headline=capndesign%20is%20still%20ginatrapani%27s%20Instagram%20bestie&body=BFFs%20tell%20each%20other%20what%20they%20think%2C%20and%20for%20%3Cstrong%3E3%20months%20straight%3C%2Fstrong%3E%20capndesign%20has%20been%20ginatrapani%27s%20Instagram%20bestie.%20In%20the%20past%20month%2C%20capndesign%20commented%20on%20ginatrapani%27s%20Instagram%20photos%2010%20times%2C%20more%20than%20anyone%20else.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=creamsicle&embed=embed-none&preview=1)

[Edit this](https://thinkup.thinkup.com/insight_tester.php?headline=capndesign%20is%20still%20ginatrapani%27s%20Instagram%20bestie&body=BFFs%20tell%20each%20other%20what%20they%20think%2C%20and%20for%20%3Cstrong%3E3%20months%20straight%3C%2Fstrong%3E%20capndesign%20has%20been%20ginatrapani%27s%20Instagram%20bestie.%20In%20the%20past%20month%2C%20capndesign%20commented%20on%20ginatrapani%27s%20Instagram%20photos%2010%20times%2C%20more%20than%20anyone%20else.%20What%20a%20pair!%20Alt%20endings%3A%20You%20two!%20Peas%20in%20a%20pod!%20Best%20buds%20forever!%20Best%20pals!%20OMG%20get%20a%20room!&button=Action!&avatar=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1096005346%2F1_normal.jpg&hero=https%3A%2F%2Fwww.thinkup.com%2Fassets%2Fimages%2Finsights%2F2014-05%2Fsubway.jpg&show-button=false&show-avatar=true&show-emphasis=false&show-hero=false&show-wide=true&color=mint&embed=embed-none&preview=1)

# Criteria and logic

* Use the PostDAO::getBestie function to determine bestie. Criteria is slightly different for Facebook and Twitter due to crawler capture differences.
* If there aren't enough interactions to justify "bestie", don't show the insight at all.
* Do store this month's bestie and compare it against last month's for a baseline comparison.

# Included elements

- [x] Headline
- [x] Text
- [x] Header image (image off to the left in side-by-side style insights) - bestie avatar
- [ ] Hero image (giant image on top)
- [ ] List of user(s)
- [ ] List of post(s)
- [ ] List of link(s)
- [ ] Action button
- [ ] Line chart
- [ ] Bar chart
- [ ] Other viz
- [ ] Other graphic treatment

**Comment by ginatrapani** [comment]
Committed in https://github.com/ThinkUpLLC/ThinkUp/commit/cf794bc19a1c80a5910407909f6407af426e4b04
