### ISSUE TITLE
Import/backfill Foursquare history

### ISSUE THREAD

**Issue by dgw** [ThinkUpLLC/ThinkUp#2094]
Since Foursquare's API allows access to the user's entire history, without the paging limit that afflicts Twitter (and eventually inspired #1413), I see no reason that the Foursquare plugin should limit itself to retrieving only the most recent 250 checkins.

Foursquare also provides feeds (see https://foursquare.com/feeds/), and the ICS feed could be a starting point for a manually-run importer. It contains basic details (checkin UID, venue name, geo coords, checkin timestamp) that could be used to fetch the rest of the details during crawler runs, a few at a time.

**Comment by ginatrapani** [comment]
We removed Foursquare support from the core repository for now in the master branch update: http://blog.thinkup.com/post/109954921177/developers-thinkups-master-branch-is-up-to-date
