### ISSUE TITLE
Made the List Trim Link in Twitter Plugin Malfunction

### ISSUE THREAD

**Issue by weems** [ThinkUpLLC/ThinkUp#2124]
On the following page [http://thinkup/?u=________&n=twitter&d=2014-10-16&s=new_group_memberships](http://thinkup/?u=[]][[]][[]&n=twitter&d=2014-10-16&s=new_group_memberships)

**Comment by ginatrapani** [comment]
Hi - I can't see this URL. Can you provide a screenshot or description of the problem?

**Comment by weems** [comment]
I can't reproduce now, should have captured it at the time. I shall do some more testing.
