### ISSUE TITLE
Update GitHub repository URL

### ISSUE THREAD

**Issue by ginatrapani** [ThinkUpLLC/ThinkUp#2206]
The ThinkUp GitHub repository has moved to https://github.com/ThinkUpLLC/ThinkUp. All links in the app itself, and the documentation (*.rst files) should get updated.

**Comment by kushalxp** [comment]
Hi gina,
how would one will find how many files contains github repo url as the are more then thousands of file in the app ?

**Comment by ginatrapani** [comment]
Try a global search and replace in a good text editor.

**Comment by kushalxp** [comment]
Fixed #2217 
here is my pull request: https://github.com/ThinkUpLLC/ThinkUp/pull/2217
Thank you :)
