### ISSUE TITLE
Thinkup folder permission issue warning in daily email update

### ISSUE THREAD

**Issue by todoleo** [ThinkUpLLC/ThinkUp#2209]
The Thinkup daily email update has folder permission warning as body.

Observed on February 3rd 2015 at 10:35 UTC:

>ThinkUp <team@thinkup.com>
>	
>10:35 (1 hour ago)
>		
>To me
>ThinkUp
>Uh oh! ThinkUp can't write some necessary files.
>
>Oops! ThinkUp is unable to run because of incorrect folder permissions.
>
>To fix this problem, run
>sudo chown -R root /home/ubuntu/userdata/todoleo/
>on your server, using root (or sudo), and then reload this page to continue.
>
>If you don't have root access, use the following command instead:
>chmod -R 777 /home/ubuntu/userdata/todoleo/
>
>Back to top
>
>ThinkUp • Documentation • Mailing List • Old-School Dashboard
>
>© ThinkUp LLC 2012-2015. It is nice to be nice.
>
>

Please also see the attached screenshot taken from the Gmail app on a mobile device.

![screenshot_2015-02-03-11-36-55](https://cloud.githubusercontent.com/assets/10829455/6019555/b791985c-ab99-11e4-8b62-9ff8b7abba6f.png)

Thanks for the great product, let me know if you need any help retesting. :-)

Matteo

**Comment by ginatrapani** [comment]
Apologies!  Tomorrow's email will be fixed.
