### ISSUE TITLE
Email error: "ThinkUp can't write some necessary files."

### ISSUE THREAD

**Issue by dieseltravis** [ThinkUpLLC/ThinkUp#2210]
Email Text:

> Uh oh! ThinkUp can't write some necessary files.
> 
> Oops! ThinkUp is unable to run because of incorrect folder permissions.
> 
> To fix this problem, run
> `sudo chown -R root /home/ubuntu/userdata/travishardiman/`
> on your server, using root (or sudo), and then reload this page to continue.
> 
> If you don't have root access, use the following command instead:
> `chmod -R 777 /home/ubuntu/userdata/travishardiman/`

Screenshot:

![image](https://cloud.githubusercontent.com/assets/17863/6023417/bc059872-ab92-11e4-9579-44926b727fda.png)

**Comment by ginatrapani** [comment]
Apologies. This has been fixed - tomorrow's email will have all the permissions it needs.

**Comment by dieseltravis** [comment]
Cool, thanks! :smile:
