### ISSUE TITLE
New Insight: [Weekly Instagram Max count]

### ISSUE THREAD

**Issue by Bytemarks** [ThinkUpLLC/ThinkUp#2214]
# One-liner

*The image that got you the most "likes" this past week

![Insight preview](https://shares.thinkup.com/insight?headline=%40Bytemarks%20most%20popular%20Instagram%20post%20this%20week&body=%40Bytemarks%20had%20a%20total%20of%20%20%3Cstrong%3E233%3C%2Fstrong%3E%20likes%20this%20week.%20That%27s%20compared%20to%2032%20likes%20last%20week.%20Way%20to%20pump%20up%20the%20volume!&button=Share%20a%20kitten&avatar=https%3A%2F%2Ffarm9.staticflickr.com%2F8611%2F16217920799_6f1c1372b9.jpg&hero=https%3A%2F%2Ffarm9.staticflickr.com%2F8635%2F15703541353_2bb0b18321.jpg&show-button=false&show-avatar=true&show-emphasis=true&show-hero=true&show-wide=false&color=creamsicle&network=instagram&embed=show-pie&preview=1)
[Insight preview](https://thinkup.thinkup.com/insight_creator.php?headline=%40Bytemarks%20most%20popular%20Instagram%20post%20this%20week&body=%40Bytemarks%20had%20a%20total%20of%20%20%3Cstrong%3E233%3C%2Fstrong%3E%20likes%20this%20week.%20That%27s%20compared%20to%2032%20likes%20last%20week.%20Way%20to%20pump%20up%20the%20volume!&button=Share%20a%20kitten&avatar=https%3A%2F%2Ffarm9.staticflickr.com%2F8611%2F16217920799_6f1c1372b9.jpg&hero=https%3A%2F%2Ffarm9.staticflickr.com%2F8635%2F15703541353_2bb0b18321.jpg&show-button=false&show-avatar=true&show-emphasis=true&show-hero=true&show-wide=false&color=creamsicle&network=instagram&embed=show-pie&preview=1)

# Full explainer

Provides user insight in to what kinds of images provide the most likes.

# Audience for the insight

Which networks, if any, are excluded from this insight? None

Does this insight serve users with less or more activity? More acitivity

First-run: does this insight show up on a user's first crawl? Yes

# How often this insight runs

- [ ] Always (triggered by a data event, check the data and update insight on every crawl)
- [ ] Daily (check the data once a day, don't regenerate every crawl)
- [ X] Weekly on a fixed day (specify day of week per network to space these out)
- [ ] Monthly on a fixed day with bonus magic day within first 2 weeks of use (specify day of month per network to space these out)
- [ ] Annual on a fixed date (specify day of year)
- [ ] Annual every 365 days from first appearance

# Headline

@Bytemarks most popular Instagram post this week

Include multiple variations, use third person and variables for localized network terminology.

For example:

* %username has passed %total %followers!
* More than %total people are %following %username

# Body

@Bytemarks had a total of  <strong>233</strong> likes this week. That's compared to 32 likes last week. Way to pump up the volume!

Include multiple variations whenever possible.

For example:

* This week's top image got 20 more likes this week than your top image last week.

# Tout

undefined

Explain how ThinkUp can help potential users, basing copy on the insight.

For example:

* Want a handy list of the links you've favorited? We can help!
* Get a look back at what you were doing on this day in years past.

# Criteria and logic

Describe the rules for when this insight runs.

* This insight needs to count the number likes for images throughout the week and determine the max count.

## Emphasis

- [x] High
- [ ] Medium
- [ ] Low

# Included elements

- [x] Headline
- [x] Text
- [x] Header image (image off to the left in side-by-side style insights: https://farm9.staticflickr.com/8611/16217920799_6f1c1372b9.jpg)
- [x] Hero image (giant image on top)
- [ ] List of user(s)
- [ ] List of post(s)
- [ ] List of link(s)
- [ ] Action button (please specify button label and URL button should link to)
- [ ] Line chart
- [ ] Bar chart
- [ ] Other viz
- [ ] Other graphic treatment

## Action button

Specify the following action button attributes:

* 'label' => 'Go to Instagram image',
* 'url' => 'http://instagram.com/p/yve1JWy23d/?modal=true',

## Hero image

If your insight includes a hero image, we encourage you to use public domain or CC-licensed images. Hero images should be at least 540px wide and be landscape. (They can be portrait, but then they're quite tall.)

Specify the following hero image attributes:

* 'url' => 'https://www.thinkup.com/assets/images/insights/2014-03/oscars2014.jpg',
* 'alt_text' => 'Ellen DeGeneres posted the most popular tweet of all time',
* 'credit' => 'Photo: @TheEllenShow',
* 'img_link' => 'https://twitter.com/TheEllenShow/status/440322224407314432'

**Comment by ginatrapani** [comment]
Yes! This is a great idea. The existing "weekly best" insight works with Instagram data now. You can see it in action here: https://demo.thinkup.com/ginatrapani/?u=ginatrapani&n=instagram&d=2015-02-15&s=weekly_best
