### ISSUE TITLE
TMP Write Issue

### ISSUE THREAD

**Issue by thelowerworld** [ThinkUpLLC/ThinkUp#2231]
In having an issue with installer ThinkUp into a shared hosting plan that requires that the TMP folder to be writable. Was hoping in that there could be a way or someone knowledgable to have the installer look into having it see /home/username/tmp

**Comment by ginatrapani** [comment]
Here's how to configure that path: https://www.thinkup.com/docs/install/advancedconfig.html#datadir-path
