### ISSUE TITLE
Update application favicon

### ISSUE THREAD

**Issue by ginatrapani** [ThinkUpLLC/ThinkUp#301]
Gina has the new version.

Also update: thinkupapp.com favicon, mailing list icon, Twitter icon, Facebook page icon.

**Comment by charliepark** [comment]
Gina, I'd love to get the favicon to be retina-friendly for you, so it isn't pixelated on retina screens.

![screen shot 2015-02-14 at 3 09 17 pm](https://cloud.githubusercontent.com/assets/22547/6201417/430d52a6-b45d-11e4-82ff-3d0a386ce9a5.png)

If you have a larger version of that image (anything not-pixelated and over 48px x 48px will work), I can whip that up and get it back to you. Let me know?

**Comment by ginatrapani** [comment]
Hi @charliepark - we've had "Make favicon less janky" (exact words) on our internal project list since August. 

It turns out that particular TU is out of date, b/c we don't use the black U anymore. This is our current, high-res logo:  https://www.thinkup.com/join/assets/img/thinkup-logo-hires.png

We've been meaning to convert that into a new favicon for months. If you're willing and able to do that - and update all versions - we'd be grateful!

**Comment by charliepark** [comment]
Awesome. Do you know the font / weights you're using there? It actually might yield an even better result if I type the "T" and "U" into Photoshop directly. I can try it just with that logo, for sure. Not trying to create more work for you. :)

**Comment by ginatrapani** [comment]
Lemme check with @anildash re: font. More soon!

**Comment by charliepark** [comment]
Actually, might not be necessary. LMK what you think about the one on the right:
![screen shot 2015-02-15 at 6 33 40 pm](https://cloud.githubusercontent.com/assets/22547/6206531/40c0aaf4-b541-11e4-8e4a-a2e580c64af0.png)

**Comment by charliepark** [comment]
(I can also make the letters touch, if you'd prefer that.)

**Comment by ginatrapani** [comment]
Wow, what an improvement! I love it. I like it without the letters touching. Thank you!

**Comment by charliepark** [comment]
Awesome! Will open a separate PR.

**Comment by anildash** [comment]
Seems like you figured it out @charliepark, but it's just standard Helvetica Neue, in Bold for "Think" and Light for "Up".
